service: whatstheworkoutservice

provider:
  name: aws
  runtime: dotnetcore2.1
  region: us-east-2

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  api:
    handler: WhatsTheWorkout::WhatsTheWorkout.LambdaEntryPoint::FunctionHandlerAsync
    events:
     - http:
         path: /{proxy+}
         method: ANY